export const ingredientFilters = {
  "Source & Ethics": [
    "Natural / Naturally-derived",
    "Organic / Certified Organic",
    "Vegan (no animal-derived ingredients)",
    "Cruelty-Free (not tested on animals)",
    "Halal-certified",
    "Kosher-certified",
    "Fair Trade / Ethically sourced",
    "Palm-free / RSPO-certified (sustainable palm oil)",
  ],
  "Functionality & Performance": [
    "Emollient / Moisturizer",
    "Humectant",
    "Preservative (natural/synthetic)",
    "Surfactant (cleansing agent)",
    "Emulsifier",
    "Thickener / Stabilizer",
    "Film former",
    "SPF booster / UV filter",
    "Colorant / Pigment",
    "Active ingredient (e.g., anti-aging, brightening)",
  ],
  "Ingredient Classifications": [
    "Silicone-free",
    "Paraben-free",
    "Sulfate-free (e.g., SLS, SLES)",
    "PEG-free",
    "Mineral oil-free",
    "Alcohol-free",
    "Fragrance-free",
    "Essential oil-free",
    "Allergen-free (per EU or other standards)",
  ],
  "Skin Sensitivity & Safety": [
    "Dermatologically tested",
    "Non-comedogenic",
    "Hypoallergenic",
    "pH-balanced",
    "EU 26 fragrance allergen-free",
    "Free from microplastics",
    "Free from nanoparticles",
    "Endocrine disruptor-free",
    "Safe for pregnancy",
  ],
  "Regulatory & Certification": [
    "COSMOS-approved",
    "ECOCERT-certified",
    "EWG Verified / EWG score",
    "REACH-compliant (EU)",
    "FDA-approved / GRAS (US)",
    "China-compliant (no animal testing required)",
    "ISO 16128 (natural content standard)",
  ],
  "Sustainability & Environmental Impact": [
    "Biodegradable",
    "Upcycled / Byproduct-derived",
    "Waterless / anhydrous",
    "Low carbon footprint",
    "Locally sourced / Regional",
    "Eco-friendly packaging compatible",
    "Sustainable harvesting / cultivation",
    "Ocean-safe (reef-safe for sunscreens)",
  ],
};
